# Generated by Django 5.2 on 2025-04-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='return_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
