# Generated by Django 5.2 on 2025-04-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_issuerequest_return_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
