# Generated by Django 5.2 on 2025-04-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_issuerequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
