# Generated by Django 5.2 on 2025-04-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_issuerequest_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
