# Generated by Django 5.2 on 2025-04-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_issuerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='fine_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='fine_payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='fine_payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='fine_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid_online', 'Paid Online'), ('paid_cash', 'Paid Cash'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
