# Generated by Django 5.2 on 2025-04-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_issuerequest_fine_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
